/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.telas;

import br.edu.DAO.EspecialidadeDAO;
import br.edu.anotacoes.Especialidade;
import javax.swing.JOptionPane;

/**
 *
 * @author Lab3
 */
public class CadastrarEspecialidade extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarEspecialidade
     */
    public CadastrarEspecialidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jL_consultas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jL_hora = new javax.swing.JLabel();
        jT_especialidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_consultas.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jL_consultas.setForeground(new java.awt.Color(255, 255, 255));
        jL_consultas.setText("Especialidades");
        jPanel2.add(jL_consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 370, 44));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 390, 60));

        jPanel1.setBackground(new java.awt.Color(67, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jL_hora.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jL_hora.setText("Especialidade");
        jPanel1.add(jL_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 20));

        jT_especialidade.setBorder(null);
        jPanel1.add(jT_especialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean testarVazio(){
        if(jT_especialidade.getText().isEmpty()){
            return false;
        }else{
            return true;
        }
    }
    
    private boolean salvar(){
        Especialidade especialidade = new Especialidade(
                jT_especialidade.getText()
        );
        EspecialidadeDAO especialidadeDAO = new EspecialidadeDAO();
        try {
            especialidadeDAO.salvar(especialidade);
        } catch (Exception e) {
            System.out.println("Erro no cadastro de especialidade: " + e);
            return false;
        }
        JOptionPane.showMessageDialog(null, "Especialidade Cadastrada com sucesso");
        return true;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (testarVazio()) {
            salvar();
        } else {
            JOptionPane.showMessageDialog(null, "Especialidade em branco");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarEspecialidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarEspecialidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jL_consultas;
    private javax.swing.JLabel jL_hora;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jT_especialidade;
    // End of variables declaration//GEN-END:variables
}
