/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.telas;

import br.edu.util.ControleTelas;
import br.edu.util.Util;
import com.sun.webkit.event.WCKeyEvent;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.border.DropShadowBorder;


/**
 *
 * @author Lab1
 */


public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_container = new javax.swing.JPanel();
        jL_recepcionista = new javax.swing.JLabel();
        jL_cliente = new javax.swing.JLabel();
        jL_funcionario = new javax.swing.JLabel();
        jP_funcionario = new javax.swing.JPanel();
        jP_listarFuncionario = new javax.swing.JPanel();
        jL_listarFuncionario = new javax.swing.JLabel();
        jP_cadastrarFuncionario = new javax.swing.JPanel();
        jL_cadastrarFuncionario = new javax.swing.JLabel();
        jL_admin = new javax.swing.JLabel();
        jP_sair = new javax.swing.JPanel();
        jL_iconSair = new javax.swing.JLabel();
        jL_sair = new javax.swing.JLabel();
        jP_administrador = new javax.swing.JPanel();
        jP_listarAdmin = new javax.swing.JPanel();
        jL_listarAdmin = new javax.swing.JLabel();
        jP_cadastrarAdmin = new javax.swing.JPanel();
        jL_cadastrarAdmin = new javax.swing.JLabel();
        jP_cliente = new javax.swing.JPanel();
        jP_listarCliente = new javax.swing.JPanel();
        jL_listarCliente = new javax.swing.JLabel();
        jP_cadastrarCliente = new javax.swing.JPanel();
        jL_cadastrarCliente = new javax.swing.JLabel();
        jP_cliente1 = new javax.swing.JPanel();
        jP_listarRecepcionista = new javax.swing.JPanel();
        jL_listarRecepcionista = new javax.swing.JLabel();
        jP_cadastrarRecepcionista = new javax.swing.JPanel();
        jL_cadastrarRecepcionista = new javax.swing.JLabel();
        jP_CadastrarMedicos = new javax.swing.JPanel();
        jP_listarMedicos = new javax.swing.JPanel();
        jL_listarMedico = new javax.swing.JLabel();
        jP_cadastraMedicos = new javax.swing.JPanel();
        jL_cadastrarMedico = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel1 = new javax.swing.JLabel();
        jYearChooser2 = new com.toedter.calendar.JYearChooser();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_container.setBackground(new java.awt.Color(0, 102, 102));
        jP_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_recepcionista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_recepcionista.setForeground(new java.awt.Color(240, 240, 240));
        jL_recepcionista.setText("Recepcionista");
        jP_container.add(jL_recepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 219, -1, -1));

        jL_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_cliente.setForeground(new java.awt.Color(240, 240, 240));
        jL_cliente.setText("Cliente");
        jP_container.add(jL_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jL_funcionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_funcionario.setForeground(new java.awt.Color(240, 240, 240));
        jL_funcionario.setText("Especialidade");
        jP_container.add(jL_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jP_funcionario.setBackground(new java.awt.Color(36, 47, 65));
        jP_funcionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jP_listarFuncionario.setBackground(new java.awt.Color(0, 102, 102));
        jP_listarFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_listarFuncionario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarFuncionarioMouseMoved(evt);
            }
        });
        jP_listarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarFuncionarioMouseExited(evt);
            }
        });
        jP_listarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_listarFuncionario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_listarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jL_listarFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_listarFuncionario.setText("Listar");
        jL_listarFuncionario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_listarFuncionarioMouseMoved(evt);
            }
        });
        jL_listarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_listarFuncionarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_listarFuncionarioMouseExited(evt);
            }
        });
        jP_listarFuncionario.add(jL_listarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        jP_cadastrarFuncionario.setBackground(new java.awt.Color(0, 102, 102));
        jP_cadastrarFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_cadastrarFuncionario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarFuncionarioMouseMoved(evt);
            }
        });
        jP_cadastrarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarFuncionarioMouseExited(evt);
            }
        });
        jP_cadastrarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_cadastrarFuncionario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_cadastrarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastrarFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_cadastrarFuncionario.setText("Cadastrar");
        jL_cadastrarFuncionario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_cadastrarFuncionarioMouseMoved(evt);
            }
        });
        jL_cadastrarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_cadastrarFuncionarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_cadastrarFuncionarioMouseExited(evt);
            }
        });
        jP_cadastrarFuncionario.add(jL_cadastrarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        javax.swing.GroupLayout jP_funcionarioLayout = new javax.swing.GroupLayout(jP_funcionario);
        jP_funcionario.setLayout(jP_funcionarioLayout);
        jP_funcionarioLayout.setHorizontalGroup(
            jP_funcionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_funcionarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jP_funcionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_cadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_listarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jP_funcionarioLayout.setVerticalGroup(
            jP_funcionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_funcionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_cadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jP_listarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jP_container.add(jP_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 280, 160));

        jL_admin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_admin.setForeground(new java.awt.Color(240, 240, 240));
        jL_admin.setText("Administrador");
        jP_container.add(jL_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jP_sair.setBackground(new java.awt.Color(36, 47, 65));
        jP_sair.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_sairMouseMoved(evt);
            }
        });
        jP_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_sairMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_sairMouseExited(evt);
            }
        });
        jP_sair.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jP_sair.add(jL_iconSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 29, -1, -1));

        jL_sair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_sair.setForeground(new java.awt.Color(255, 255, 255));
        jL_sair.setText("         Logout");
        jL_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_sair.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_sairMouseMoved(evt);
            }
        });
        jL_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_sairMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_sairMouseExited(evt);
            }
        });
        jP_sair.add(jL_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 90, 40));

        jP_container.add(jP_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 90, 40));

        jP_administrador.setBackground(new java.awt.Color(36, 47, 65));
        jP_administrador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jP_listarAdmin.setBackground(new java.awt.Color(0, 102, 102));
        jP_listarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_listarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarAdminMouseMoved(evt);
            }
        });
        jP_listarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarAdminMouseExited(evt);
            }
        });
        jP_listarAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_listarAdmin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_listarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jL_listarAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_listarAdmin.setText("Listar");
        jL_listarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_listarAdminMouseMoved(evt);
            }
        });
        jL_listarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_listarAdminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_listarAdminMouseExited(evt);
            }
        });
        jP_listarAdmin.add(jL_listarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        jP_cadastrarAdmin.setBackground(new java.awt.Color(0, 102, 102));
        jP_cadastrarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_cadastrarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarAdminMouseMoved(evt);
            }
        });
        jP_cadastrarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarAdminMouseExited(evt);
            }
        });
        jP_cadastrarAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_cadastrarAdmin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_cadastrarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastrarAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_cadastrarAdmin.setText("Cadastrar");
        jL_cadastrarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_cadastrarAdminMouseMoved(evt);
            }
        });
        jL_cadastrarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_cadastrarAdminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_cadastrarAdminMouseExited(evt);
            }
        });
        jP_cadastrarAdmin.add(jL_cadastrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        javax.swing.GroupLayout jP_administradorLayout = new javax.swing.GroupLayout(jP_administrador);
        jP_administrador.setLayout(jP_administradorLayout);
        jP_administradorLayout.setHorizontalGroup(
            jP_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_administradorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jP_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_cadastrarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_listarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jP_administradorLayout.setVerticalGroup(
            jP_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_administradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_cadastrarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jP_listarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jP_container.add(jP_administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 160));

        jP_cliente.setBackground(new java.awt.Color(36, 47, 65));
        jP_cliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jP_listarCliente.setBackground(new java.awt.Color(0, 102, 102));
        jP_listarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_listarCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarClienteMouseMoved(evt);
            }
        });
        jP_listarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarClienteMouseExited(evt);
            }
        });
        jP_listarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_listarCliente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_listarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jL_listarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_listarCliente.setText("Listar");
        jL_listarCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_listarClienteMouseMoved(evt);
            }
        });
        jL_listarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_listarClienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_listarClienteMouseExited(evt);
            }
        });
        jP_listarCliente.add(jL_listarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        jP_cadastrarCliente.setBackground(new java.awt.Color(0, 102, 102));
        jP_cadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_cadastrarCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarClienteMouseMoved(evt);
            }
        });
        jP_cadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarClienteMouseExited(evt);
            }
        });
        jP_cadastrarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_cadastrarCliente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_cadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_cadastrarCliente.setText("Cadastrar");
        jL_cadastrarCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_cadastrarClienteMouseMoved(evt);
            }
        });
        jL_cadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_cadastrarClienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_cadastrarClienteMouseExited(evt);
            }
        });
        jP_cadastrarCliente.add(jL_cadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        javax.swing.GroupLayout jP_clienteLayout = new javax.swing.GroupLayout(jP_cliente);
        jP_cliente.setLayout(jP_clienteLayout);
        jP_clienteLayout.setHorizontalGroup(
            jP_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_clienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jP_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_cadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_listarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jP_clienteLayout.setVerticalGroup(
            jP_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_cadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jP_listarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jP_container.add(jP_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 280, 160));

        jP_cliente1.setBackground(new java.awt.Color(36, 47, 65));
        jP_cliente1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jP_listarRecepcionista.setBackground(new java.awt.Color(0, 102, 102));
        jP_listarRecepcionista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_listarRecepcionista.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarRecepcionistaMouseMoved(evt);
            }
        });
        jP_listarRecepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarRecepcionistaMouseExited(evt);
            }
        });
        jP_listarRecepcionista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_listarRecepcionista.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_listarRecepcionista.setForeground(new java.awt.Color(255, 255, 255));
        jL_listarRecepcionista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_listarRecepcionista.setText("Listar");
        jL_listarRecepcionista.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_listarRecepcionistaMouseMoved(evt);
            }
        });
        jL_listarRecepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_listarRecepcionistaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_listarRecepcionistaMouseExited(evt);
            }
        });
        jP_listarRecepcionista.add(jL_listarRecepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        jP_cadastrarRecepcionista.setBackground(new java.awt.Color(0, 102, 102));
        jP_cadastrarRecepcionista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_cadastrarRecepcionista.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarRecepcionistaMouseMoved(evt);
            }
        });
        jP_cadastrarRecepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarRecepcionistaMouseExited(evt);
            }
        });
        jP_cadastrarRecepcionista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_cadastrarRecepcionista.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_cadastrarRecepcionista.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastrarRecepcionista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_cadastrarRecepcionista.setText("Cadastrar");
        jL_cadastrarRecepcionista.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_cadastrarRecepcionistaMouseMoved(evt);
            }
        });
        jL_cadastrarRecepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_cadastrarRecepcionistaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_cadastrarRecepcionistaMouseExited(evt);
            }
        });
        jP_cadastrarRecepcionista.add(jL_cadastrarRecepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        javax.swing.GroupLayout jP_cliente1Layout = new javax.swing.GroupLayout(jP_cliente1);
        jP_cliente1.setLayout(jP_cliente1Layout);
        jP_cliente1Layout.setHorizontalGroup(
            jP_cliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cliente1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jP_cliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_cadastrarRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_listarRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jP_cliente1Layout.setVerticalGroup(
            jP_cliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_cliente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_cadastrarRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jP_listarRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jP_container.add(jP_cliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 280, 160));

        jP_CadastrarMedicos.setBackground(new java.awt.Color(36, 47, 65));
        jP_CadastrarMedicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jP_listarMedicos.setBackground(new java.awt.Color(0, 102, 102));
        jP_listarMedicos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_listarMedico.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_listarMedico.setForeground(new java.awt.Color(255, 255, 255));
        jL_listarMedico.setText("                      Listar");
        jL_listarMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_listarMedico.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_listarMedicoMouseMoved(evt);
            }
        });
        jL_listarMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_listarMedicoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_listarMedicoMouseExited(evt);
            }
        });
        jP_listarMedicos.add(jL_listarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -1, 220, 40));

        jP_cadastraMedicos.setBackground(new java.awt.Color(0, 102, 102));
        jP_cadastraMedicos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastraMedicosMouseMoved(evt);
            }
        });
        jP_cadastraMedicos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_cadastrarMedico.setBackground(new java.awt.Color(255, 255, 255));
        jL_cadastrarMedico.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_cadastrarMedico.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastrarMedico.setText("                       Cadastrar");
        jL_cadastrarMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_cadastrarMedico.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_cadastrarMedicoMouseMoved(evt);
            }
        });
        jL_cadastrarMedico.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jL_cadastrarMedicoMouseWheelMoved(evt);
            }
        });
        jL_cadastrarMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_cadastrarMedicoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_cadastrarMedicoMouseExited(evt);
            }
        });
        jP_cadastraMedicos.add(jL_cadastrarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 240, 40));

        javax.swing.GroupLayout jP_CadastrarMedicosLayout = new javax.swing.GroupLayout(jP_CadastrarMedicos);
        jP_CadastrarMedicos.setLayout(jP_CadastrarMedicosLayout);
        jP_CadastrarMedicosLayout.setHorizontalGroup(
            jP_CadastrarMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_CadastrarMedicosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jP_CadastrarMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jP_cadastraMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_listarMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jP_CadastrarMedicosLayout.setVerticalGroup(
            jP_CadastrarMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_CadastrarMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_cadastraMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jP_listarMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jP_container.add(jP_CadastrarMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 280, 160));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Médico");
        jP_container.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Relatorios");
        jP_container.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Geral");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Por Consulta dos medicos");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Gerar");
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel5MouseMoved(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gerar");
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jYearChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(11, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jYearChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jP_container.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 280, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_container, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_container, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(645, 693));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jL_listarFuncionarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarFuncionarioMouseMoved
        jP_listarFuncionario.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_listarFuncionarioMouseMoved

    private void jL_listarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarFuncionarioMouseClicked
        if(ControleTelas.telaListarEspecialiades == false){
            ListarEspecialidades listarEspecialidades = new ListarEspecialidades();
            listarEspecialidades.setVisible(true);
        }
    }//GEN-LAST:event_jL_listarFuncionarioMouseClicked

    private void jL_listarFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarFuncionarioMouseExited
        efeitoBordaCancelar(jP_listarFuncionario);
    }//GEN-LAST:event_jL_listarFuncionarioMouseExited

    private void jP_listarFuncionarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarFuncionarioMouseMoved
        jP_listarFuncionario.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_listarFuncionarioMouseMoved

    private void jP_listarFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarFuncionarioMouseExited
        efeitoBordaCancelar(jP_listarFuncionario);
    }//GEN-LAST:event_jP_listarFuncionarioMouseExited

    private void jL_cadastrarFuncionarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarFuncionarioMouseMoved
       jP_cadastrarFuncionario.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_cadastrarFuncionarioMouseMoved

    private void jL_cadastrarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarFuncionarioMouseClicked
       if(ControleTelas.telaCadastroEspecialidade == false){
            CadastrarEspecialidade cadastrarEspecialidade = new CadastrarEspecialidade();
            cadastrarEspecialidade.setVisible(true);
        }
    }//GEN-LAST:event_jL_cadastrarFuncionarioMouseClicked

    private void jL_cadastrarFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarFuncionarioMouseExited
        efeitoBordaCancelar(jP_cadastrarFuncionario);
    }//GEN-LAST:event_jL_cadastrarFuncionarioMouseExited

    private void jP_cadastrarFuncionarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarFuncionarioMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastrarFuncionarioMouseMoved

    private void jP_cadastrarFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarFuncionarioMouseExited
       efeitoBordaCancelar(jP_cadastrarFuncionario);
    }//GEN-LAST:event_jP_cadastrarFuncionarioMouseExited

    private void jL_listarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarAdminMouseMoved
        jP_listarAdmin.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_listarAdminMouseMoved

    private void jL_listarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarAdminMouseClicked
        if(ControleTelas.telaListarAdministrador == false){
            ListarAdmin listarAdmin = new ListarAdmin();
            listarAdmin.setVisible(true);
        }
    }//GEN-LAST:event_jL_listarAdminMouseClicked

    private void jL_listarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarAdminMouseExited
        efeitoBordaCancelar(jP_listarAdmin);
    }//GEN-LAST:event_jL_listarAdminMouseExited

    private void jP_listarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarAdminMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarAdminMouseMoved

    private void jP_listarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarAdminMouseExited

    private void jL_cadastrarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarAdminMouseMoved
        jP_cadastrarAdmin.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_cadastrarAdminMouseMoved

    private void jL_cadastrarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarAdminMouseClicked
        if(ControleTelas.telaCadastroAdmins == false){
            CadastrarAdmins cadastrarAdmins = new CadastrarAdmins();
            cadastrarAdmins.setVisible(true);
        }
    }//GEN-LAST:event_jL_cadastrarAdminMouseClicked

    private void jL_cadastrarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarAdminMouseExited
        efeitoBordaCancelar(jP_cadastrarAdmin);
    }//GEN-LAST:event_jL_cadastrarAdminMouseExited

    private void jP_cadastrarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarAdminMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastrarAdminMouseMoved

    private void jP_cadastrarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastrarAdminMouseExited

    private void jL_listarClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarClienteMouseMoved
        jP_listarCliente.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_listarClienteMouseMoved

    private void jL_listarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarClienteMouseClicked
        if(ControleTelas.telaListarClientes == false){
            ListarClientes listarClientes = new ListarClientes();
            listarClientes.setVisible(true);
        }
    }//GEN-LAST:event_jL_listarClienteMouseClicked

    private void jL_listarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarClienteMouseExited
        efeitoBordaCancelar(jP_listarCliente);
    }//GEN-LAST:event_jL_listarClienteMouseExited

    private void jP_listarClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarClienteMouseMoved
        jL_listarCliente.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_listarClienteMouseMoved

    private void jP_listarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarClienteMouseExited

    private void jL_cadastrarClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarClienteMouseMoved
        jP_cadastrarCliente.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_cadastrarClienteMouseMoved

    private void jL_cadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarClienteMouseClicked
        if(ControleTelas.telaCadastroClientes == false){
            CadastroCliente cadastroCliente = new CadastroCliente();
            cadastroCliente.setVisible(true);
        }
    }//GEN-LAST:event_jL_cadastrarClienteMouseClicked

    private void jL_cadastrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarClienteMouseExited
        efeitoBordaCancelar(jP_cadastrarCliente);
    }//GEN-LAST:event_jL_cadastrarClienteMouseExited

    private void jP_cadastrarClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarClienteMouseMoved
        jL_cadastrarCliente.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_cadastrarClienteMouseMoved

    private void jP_cadastrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarClienteMouseExited
        efeitoBordaCancelar(jP_cadastrarCliente);
    }//GEN-LAST:event_jP_cadastrarClienteMouseExited

    private void jL_listarRecepcionistaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarRecepcionistaMouseMoved
        jP_listarRecepcionista.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_listarRecepcionistaMouseMoved

    private void jL_listarRecepcionistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarRecepcionistaMouseClicked
        if(ControleTelas.telaListarRecepcionista == false){
            ListarRecepcionista listarRecepcionista = new ListarRecepcionista();
            listarRecepcionista.setVisible(true);
        }
    }//GEN-LAST:event_jL_listarRecepcionistaMouseClicked

    private void jL_listarRecepcionistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarRecepcionistaMouseExited
        efeitoBordaCancelar(jP_listarRecepcionista);
    }//GEN-LAST:event_jL_listarRecepcionistaMouseExited

    private void jP_listarRecepcionistaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarRecepcionistaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarRecepcionistaMouseMoved

    private void jP_listarRecepcionistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarRecepcionistaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarRecepcionistaMouseExited

    private void jL_cadastrarRecepcionistaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarRecepcionistaMouseMoved
        jP_cadastrarRecepcionista.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_cadastrarRecepcionistaMouseMoved

    private void jL_cadastrarRecepcionistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarRecepcionistaMouseClicked
        if(ControleTelas.telaCadastroRecepcionista == false){
            CadastroRecepcionista cadastroRecepcionista = new CadastroRecepcionista();
            cadastroRecepcionista.setVisible(true);
        }
    }//GEN-LAST:event_jL_cadastrarRecepcionistaMouseClicked

    private void jL_cadastrarRecepcionistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarRecepcionistaMouseExited
        efeitoBordaCancelar(jP_cadastrarRecepcionista);
    }//GEN-LAST:event_jL_cadastrarRecepcionistaMouseExited

    private void jP_cadastrarRecepcionistaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarRecepcionistaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastrarRecepcionistaMouseMoved

    private void jP_cadastrarRecepcionistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarRecepcionistaMouseExited
        efeitoBordaCancelar(jP_cadastrarRecepcionista);
    }//GEN-LAST:event_jP_cadastrarRecepcionistaMouseExited

    private void jP_sairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_sairMouseExited
        efeitoBordaCancelar(jP_sair);
    }//GEN-LAST:event_jP_sairMouseExited

    private void jP_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_sairMouseClicked
        this.dispose();
    }//GEN-LAST:event_jP_sairMouseClicked

    private void jP_sairMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_sairMouseMoved
        jP_sair.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_sairMouseMoved

    private void jL_sairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_sairMouseExited
        efeitoBordaCancelar(jP_sair);
    }//GEN-LAST:event_jL_sairMouseExited

    private void jL_sairMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_sairMouseMoved
        jP_sair.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_sairMouseMoved

    private void jL_cadastrarMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarMedicoMouseClicked
       if(ControleTelas.telaCadastroMedicos == false){
            CadastroMedicos cadastroMedico = new CadastroMedicos();
            cadastroMedico.setVisible(true);
        }
    }//GEN-LAST:event_jL_cadastrarMedicoMouseClicked

    private void jL_listarMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarMedicoMouseClicked
         if(ControleTelas.telaListarMedicos == false){
            ListarMedicos listarMedicos = new ListarMedicos();
            listarMedicos.setVisible(true);
        }
    }//GEN-LAST:event_jL_listarMedicoMouseClicked

    private void jL_cadastrarMedicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarMedicoMouseExited
       efeitoBordaCancelar(jP_cadastraMedicos);
    }//GEN-LAST:event_jL_cadastrarMedicoMouseExited

    private void jP_cadastraMedicosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastraMedicosMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastraMedicosMouseMoved

    private void jL_cadastrarMedicoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarMedicoMouseMoved
       jP_cadastraMedicos.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_cadastrarMedicoMouseMoved

    private void jL_listarMedicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarMedicoMouseExited
        efeitoBordaCancelar(jP_listarMedicos);
    }//GEN-LAST:event_jL_listarMedicoMouseExited

    private void jL_listarMedicoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarMedicoMouseMoved
        jP_listarMedicos.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_listarMedicoMouseMoved

    private void jL_cadastrarMedicoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jL_cadastrarMedicoMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_cadastrarMedicoMouseWheelMoved

    private void jL_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_sairMouseClicked
       if(JOptionPane.showConfirmDialog(null,"Deseja fazer logout")==0){
       Login login = new Login();
       login.setVisible(true);
       this.dispose();
       }
    }//GEN-LAST:event_jL_sairMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        try {
            HashMap parametros = new HashMap();
            parametros.put("Mes", (jMonthChooser1.getMonth() + 1));
            parametros.put("Ano", jYearChooser1.getYear());
            Util.imprimir("Relatorios\\RelatorioPorMes.jrxml", parametros);
        } catch (Exception e) {
            System.out.println("Erro na geração do prontuario " + e);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
            HashMap parametros = new HashMap();
            parametros.put("Ano", jYearChooser2.getYear());
            Util.imprimir("Relatorios\\RelatorioConsultas.jrxml", parametros);
        } catch (Exception e) {
            System.out.println("Erro na geração do prontuario " + e);
        }
       
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        efeitoBordaCancelar(jPanel2);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        efeitoBordaCancelar(jPanel3);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseMoved
        jPanel2.setBorder(efeitoBorda());
    }//GEN-LAST:event_jLabel5MouseMoved

    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved
         jPanel3.setBorder(efeitoBorda());
    }//GEN-LAST:event_jLabel6MouseMoved
    //codigo para colocar as sombras nos paineis
    private DropShadowBorder efeitoBorda(){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.black);
        shadow.setShadowSize(5);
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowBottomShadow(true);
        shadow.setShowTopShadow(true);
        return shadow;
    }
    //codigo para cancelar a borda em todas os paineis
    private void efeitoBordaCancelar(javax.swing.JPanel painel){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShowLeftShadow(false);
        shadow.setShowRightShadow(false);
        shadow.setShowBottomShadow(false);
        shadow.setShowTopShadow(false);
        
        painel.setBorder(shadow);
    }
 
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_admin;
    private javax.swing.JLabel jL_cadastrarAdmin;
    private javax.swing.JLabel jL_cadastrarCliente;
    private javax.swing.JLabel jL_cadastrarFuncionario;
    private javax.swing.JLabel jL_cadastrarMedico;
    private javax.swing.JLabel jL_cadastrarRecepcionista;
    private javax.swing.JLabel jL_cliente;
    private javax.swing.JLabel jL_funcionario;
    private javax.swing.JLabel jL_iconSair;
    private javax.swing.JLabel jL_listarAdmin;
    private javax.swing.JLabel jL_listarCliente;
    private javax.swing.JLabel jL_listarFuncionario;
    private javax.swing.JLabel jL_listarMedico;
    private javax.swing.JLabel jL_listarRecepcionista;
    private javax.swing.JLabel jL_recepcionista;
    private javax.swing.JLabel jL_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jP_CadastrarMedicos;
    private javax.swing.JPanel jP_administrador;
    private javax.swing.JPanel jP_cadastraMedicos;
    private javax.swing.JPanel jP_cadastrarAdmin;
    private javax.swing.JPanel jP_cadastrarCliente;
    private javax.swing.JPanel jP_cadastrarFuncionario;
    private javax.swing.JPanel jP_cadastrarRecepcionista;
    private javax.swing.JPanel jP_cliente;
    private javax.swing.JPanel jP_cliente1;
    private javax.swing.JPanel jP_container;
    private javax.swing.JPanel jP_funcionario;
    private javax.swing.JPanel jP_listarAdmin;
    private javax.swing.JPanel jP_listarCliente;
    private javax.swing.JPanel jP_listarFuncionario;
    private javax.swing.JPanel jP_listarMedicos;
    private javax.swing.JPanel jP_listarRecepcionista;
    private javax.swing.JPanel jP_sair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JYearChooser jYearChooser2;
    // End of variables declaration//GEN-END:variables
}
