/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.telas;

import br.edu.util.ControleTelas;
import com.sun.webkit.event.WCKeyEvent;
import java.awt.Color;
import org.jdesktop.swingx.border.DropShadowBorder;


/**
 *
 * @author Lab1
 */


public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_container = new javax.swing.JPanel();
        jL_recepcionista = new javax.swing.JLabel();
        jL_cliente = new javax.swing.JLabel();
        jL_funcionario = new javax.swing.JLabel();
        jP_funcionario = new javax.swing.JPanel();
        jP_listarFuncionario = new javax.swing.JPanel();
        jL_listarFuncionario = new javax.swing.JLabel();
        jP_cadastrarFuncionario1 = new javax.swing.JPanel();
        jL_cadastrarFuncionario = new javax.swing.JLabel();
        jL_admin = new javax.swing.JLabel();
        jP_sair = new javax.swing.JPanel();
        jL_sair = new javax.swing.JLabel();
        jL_iconSair = new javax.swing.JLabel();
        jP_administrador = new javax.swing.JPanel();
        jP_listarAdmin = new javax.swing.JPanel();
        jL_listarAdmin = new javax.swing.JLabel();
        jP_cadastrarAdmin = new javax.swing.JPanel();
        jL_cadastrarAdmin = new javax.swing.JLabel();
        jP_cliente = new javax.swing.JPanel();
        jP_listarCliente = new javax.swing.JPanel();
        jL_listarCliente = new javax.swing.JLabel();
        jP_cadastrarCliente = new javax.swing.JPanel();
        jL_cadastrarCliente = new javax.swing.JLabel();
        jP_cliente1 = new javax.swing.JPanel();
        jP_listarCliente1 = new javax.swing.JPanel();
        jL_listarCliente1 = new javax.swing.JLabel();
        jP_cadastrarCliente1 = new javax.swing.JPanel();
        jL_cadastrarCliente1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_container.setBackground(new java.awt.Color(0, 102, 102));
        jP_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_recepcionista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_recepcionista.setText("Recepcionista");
        jP_container.add(jL_recepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 219, -1, -1));

        jL_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_cliente.setText("Cliente");
        jP_container.add(jL_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jL_funcionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_funcionario.setText("Funcionário");
        jP_container.add(jL_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jP_funcionario.setBackground(new java.awt.Color(36, 47, 65));
        jP_funcionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jP_listarFuncionario.setBackground(new java.awt.Color(0, 102, 102));
        jP_listarFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jP_listarFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_listarFuncionario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarFuncionarioMouseMoved(evt);
            }
        });
        jP_listarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarFuncionarioMouseExited(evt);
            }
        });
        jP_listarFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_listarFuncionario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_listarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jL_listarFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_listarFuncionario.setText("Listar");
        jL_listarFuncionario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_listarFuncionarioMouseMoved(evt);
            }
        });
        jL_listarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_listarFuncionarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_listarFuncionarioMouseExited(evt);
            }
        });
        jP_listarFuncionario.add(jL_listarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        jP_cadastrarFuncionario1.setBackground(new java.awt.Color(0, 102, 102));
        jP_cadastrarFuncionario1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jP_cadastrarFuncionario1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_cadastrarFuncionario1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarFuncionario1MouseMoved(evt);
            }
        });
        jP_cadastrarFuncionario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarFuncionario1MouseExited(evt);
            }
        });
        jP_cadastrarFuncionario1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_cadastrarFuncionario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_cadastrarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastrarFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_cadastrarFuncionario.setText("Cadastrar");
        jL_cadastrarFuncionario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_cadastrarFuncionarioMouseMoved(evt);
            }
        });
        jL_cadastrarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_cadastrarFuncionarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_cadastrarFuncionarioMouseExited(evt);
            }
        });
        jP_cadastrarFuncionario1.add(jL_cadastrarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        javax.swing.GroupLayout jP_funcionarioLayout = new javax.swing.GroupLayout(jP_funcionario);
        jP_funcionario.setLayout(jP_funcionarioLayout);
        jP_funcionarioLayout.setHorizontalGroup(
            jP_funcionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_funcionarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jP_funcionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_cadastrarFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_listarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jP_funcionarioLayout.setVerticalGroup(
            jP_funcionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_funcionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_cadastrarFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jP_listarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jP_container.add(jP_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 280, 160));

        jL_admin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_admin.setText("Administrador");
        jP_container.add(jL_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jP_sair.setBackground(new java.awt.Color(0, 102, 102));

        jL_sair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jL_sair.setForeground(new java.awt.Color(255, 255, 255));
        jL_sair.setText("Sair");

        jL_iconSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lab1\\Documents\\NetBeansProjects\\Consultorio\\Icones\\50\\Sair.png")); // NOI18N

        javax.swing.GroupLayout jP_sairLayout = new javax.swing.GroupLayout(jP_sair);
        jP_sair.setLayout(jP_sairLayout);
        jP_sairLayout.setHorizontalGroup(
            jP_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_sairLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_sairLayout.createSequentialGroup()
                        .addComponent(jL_sair)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_sairLayout.createSequentialGroup()
                        .addComponent(jL_iconSair)
                        .addContainerGap())))
        );
        jP_sairLayout.setVerticalGroup(
            jP_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_sairLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_iconSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_sair)
                .addContainerGap())
        );

        jP_container.add(jP_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        jP_administrador.setBackground(new java.awt.Color(36, 47, 65));
        jP_administrador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jP_listarAdmin.setBackground(new java.awt.Color(0, 102, 102));
        jP_listarAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jP_listarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_listarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarAdminMouseMoved(evt);
            }
        });
        jP_listarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarAdminMouseExited(evt);
            }
        });
        jP_listarAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_listarAdmin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_listarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jL_listarAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_listarAdmin.setText("Listar");
        jL_listarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_listarAdminMouseMoved(evt);
            }
        });
        jL_listarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_listarAdminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_listarAdminMouseExited(evt);
            }
        });
        jP_listarAdmin.add(jL_listarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        jP_cadastrarAdmin.setBackground(new java.awt.Color(0, 102, 102));
        jP_cadastrarAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jP_cadastrarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_cadastrarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarAdminMouseMoved(evt);
            }
        });
        jP_cadastrarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarAdminMouseExited(evt);
            }
        });
        jP_cadastrarAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_cadastrarAdmin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_cadastrarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastrarAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_cadastrarAdmin.setText("Cadastrar");
        jL_cadastrarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_cadastrarAdminMouseMoved(evt);
            }
        });
        jL_cadastrarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_cadastrarAdminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_cadastrarAdminMouseExited(evt);
            }
        });
        jP_cadastrarAdmin.add(jL_cadastrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        javax.swing.GroupLayout jP_administradorLayout = new javax.swing.GroupLayout(jP_administrador);
        jP_administrador.setLayout(jP_administradorLayout);
        jP_administradorLayout.setHorizontalGroup(
            jP_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_administradorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jP_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_cadastrarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_listarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jP_administradorLayout.setVerticalGroup(
            jP_administradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_administradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_cadastrarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jP_listarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jP_container.add(jP_administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 160));

        jP_cliente.setBackground(new java.awt.Color(36, 47, 65));
        jP_cliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jP_listarCliente.setBackground(new java.awt.Color(0, 102, 102));
        jP_listarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jP_listarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_listarCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarClienteMouseMoved(evt);
            }
        });
        jP_listarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarClienteMouseExited(evt);
            }
        });
        jP_listarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_listarCliente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_listarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jL_listarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_listarCliente.setText("Listar");
        jL_listarCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_listarClienteMouseMoved(evt);
            }
        });
        jL_listarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_listarClienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_listarClienteMouseExited(evt);
            }
        });
        jP_listarCliente.add(jL_listarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 40));

        jP_cadastrarCliente.setBackground(new java.awt.Color(0, 102, 102));
        jP_cadastrarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jP_cadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_cadastrarCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarClienteMouseMoved(evt);
            }
        });
        jP_cadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarClienteMouseExited(evt);
            }
        });
        jP_cadastrarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_cadastrarCliente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_cadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_cadastrarCliente.setText("Cadastrar");
        jL_cadastrarCliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_cadastrarClienteMouseMoved(evt);
            }
        });
        jL_cadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_cadastrarClienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_cadastrarClienteMouseExited(evt);
            }
        });
        jP_cadastrarCliente.add(jL_cadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 40));

        javax.swing.GroupLayout jP_clienteLayout = new javax.swing.GroupLayout(jP_cliente);
        jP_cliente.setLayout(jP_clienteLayout);
        jP_clienteLayout.setHorizontalGroup(
            jP_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_clienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jP_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_cadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_listarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jP_clienteLayout.setVerticalGroup(
            jP_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_cadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jP_listarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jP_container.add(jP_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 280, 160));

        jP_cliente1.setBackground(new java.awt.Color(36, 47, 65));
        jP_cliente1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jP_listarCliente1.setBackground(new java.awt.Color(0, 102, 102));
        jP_listarCliente1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jP_listarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_listarCliente1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarCliente1MouseMoved(evt);
            }
        });
        jP_listarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarCliente1MouseExited(evt);
            }
        });
        jP_listarCliente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_listarCliente1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_listarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        jL_listarCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_listarCliente1.setText("Listar");
        jL_listarCliente1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_listarCliente1MouseMoved(evt);
            }
        });
        jL_listarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_listarCliente1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_listarCliente1MouseExited(evt);
            }
        });
        jP_listarCliente1.add(jL_listarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 40));

        jP_cadastrarCliente1.setBackground(new java.awt.Color(0, 102, 102));
        jP_cadastrarCliente1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jP_cadastrarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_cadastrarCliente1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarCliente1MouseMoved(evt);
            }
        });
        jP_cadastrarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarCliente1MouseExited(evt);
            }
        });
        jP_cadastrarCliente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_cadastrarCliente1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_cadastrarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastrarCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_cadastrarCliente1.setText("Cadastrar");
        jL_cadastrarCliente1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_cadastrarCliente1MouseMoved(evt);
            }
        });
        jL_cadastrarCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_cadastrarCliente1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_cadastrarCliente1MouseExited(evt);
            }
        });
        jP_cadastrarCliente1.add(jL_cadastrarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 40));

        javax.swing.GroupLayout jP_cliente1Layout = new javax.swing.GroupLayout(jP_cliente1);
        jP_cliente1.setLayout(jP_cliente1Layout);
        jP_cliente1Layout.setHorizontalGroup(
            jP_cliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cliente1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jP_cliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_cadastrarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_listarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jP_cliente1Layout.setVerticalGroup(
            jP_cliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_cliente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_cadastrarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jP_listarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jP_container.add(jP_cliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 280, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_container, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(645, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jL_listarFuncionarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarFuncionarioMouseMoved
        jL_listarFuncionario.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_listarFuncionarioMouseMoved

    private void jL_listarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarFuncionarioMouseClicked

    }//GEN-LAST:event_jL_listarFuncionarioMouseClicked

    private void jL_listarFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarFuncionarioMouseExited
        efeitoBordaCancelar(jP_listarFuncionario);
    }//GEN-LAST:event_jL_listarFuncionarioMouseExited

    private void jP_listarFuncionarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarFuncionarioMouseMoved
        jP_listarFuncionario.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_listarFuncionarioMouseMoved

    private void jP_listarFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarFuncionarioMouseExited
        efeitoBordaCancelar(jP_listarFuncionario);
    }//GEN-LAST:event_jP_listarFuncionarioMouseExited

    private void jL_cadastrarFuncionarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarFuncionarioMouseMoved
       jL_cadastrarFuncionario.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_cadastrarFuncionarioMouseMoved

    private void jL_cadastrarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarFuncionarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_cadastrarFuncionarioMouseClicked

    private void jL_cadastrarFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarFuncionarioMouseExited
        efeitoBordaCancelar(jP_cadastrarFuncionario1);
    }//GEN-LAST:event_jL_cadastrarFuncionarioMouseExited

    private void jP_cadastrarFuncionario1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarFuncionario1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastrarFuncionario1MouseMoved

    private void jP_cadastrarFuncionario1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarFuncionario1MouseExited
       efeitoBordaCancelar(jP_cadastrarFuncionario1);
    }//GEN-LAST:event_jP_cadastrarFuncionario1MouseExited

    private void jL_listarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarAdminMouseMoved
        jP_listarAdmin.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_listarAdminMouseMoved

    private void jL_listarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarAdminMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_listarAdminMouseClicked

    private void jL_listarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarAdminMouseExited
        efeitoBordaCancelar(jP_listarAdmin);
    }//GEN-LAST:event_jL_listarAdminMouseExited

    private void jP_listarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarAdminMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarAdminMouseMoved

    private void jP_listarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarAdminMouseExited

    private void jL_cadastrarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarAdminMouseMoved
        jP_cadastrarAdmin.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_cadastrarAdminMouseMoved

    private void jL_cadastrarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarAdminMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_cadastrarAdminMouseClicked

    private void jL_cadastrarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarAdminMouseExited
        efeitoBordaCancelar(jP_cadastrarAdmin);
    }//GEN-LAST:event_jL_cadastrarAdminMouseExited

    private void jP_cadastrarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarAdminMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastrarAdminMouseMoved

    private void jP_cadastrarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastrarAdminMouseExited

    private void jL_listarClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarClienteMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_listarClienteMouseMoved

    private void jL_listarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_listarClienteMouseClicked

    private void jL_listarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_listarClienteMouseExited

    private void jP_listarClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarClienteMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarClienteMouseMoved

    private void jP_listarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarClienteMouseExited

    private void jL_cadastrarClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarClienteMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_cadastrarClienteMouseMoved

    private void jL_cadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_cadastrarClienteMouseClicked

    private void jL_cadastrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_cadastrarClienteMouseExited

    private void jP_cadastrarClienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarClienteMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastrarClienteMouseMoved

    private void jP_cadastrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastrarClienteMouseExited

    private void jL_listarCliente1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarCliente1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_listarCliente1MouseMoved

    private void jL_listarCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarCliente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_listarCliente1MouseClicked

    private void jL_listarCliente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_listarCliente1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_listarCliente1MouseExited

    private void jP_listarCliente1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarCliente1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarCliente1MouseMoved

    private void jP_listarCliente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarCliente1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarCliente1MouseExited

    private void jL_cadastrarCliente1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarCliente1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_cadastrarCliente1MouseMoved

    private void jL_cadastrarCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarCliente1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_cadastrarCliente1MouseClicked

    private void jL_cadastrarCliente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cadastrarCliente1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_cadastrarCliente1MouseExited

    private void jP_cadastrarCliente1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarCliente1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastrarCliente1MouseMoved

    private void jP_cadastrarCliente1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarCliente1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_cadastrarCliente1MouseExited
    //codigo para colocar as sombras nos paineis
    private DropShadowBorder efeitoBorda(){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.black);
        shadow.setShadowSize(5);
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowBottomShadow(true);
        shadow.setShowTopShadow(true);
        return shadow;
    }
    //codigo para cancelar a borda em todas os paineis
    private void efeitoBordaCancelar(javax.swing.JPanel painel){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShowLeftShadow(false);
        shadow.setShowRightShadow(false);
        shadow.setShowBottomShadow(false);
        shadow.setShowTopShadow(false);
        
        painel.setBorder(shadow);
    }
 
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_admin;
    private javax.swing.JLabel jL_cadastrarAdmin;
    private javax.swing.JLabel jL_cadastrarCliente;
    private javax.swing.JLabel jL_cadastrarCliente1;
    private javax.swing.JLabel jL_cadastrarFuncionario;
    private javax.swing.JLabel jL_cliente;
    private javax.swing.JLabel jL_funcionario;
    private javax.swing.JLabel jL_iconSair;
    private javax.swing.JLabel jL_listarAdmin;
    private javax.swing.JLabel jL_listarCliente;
    private javax.swing.JLabel jL_listarCliente1;
    private javax.swing.JLabel jL_listarFuncionario;
    private javax.swing.JLabel jL_recepcionista;
    private javax.swing.JLabel jL_sair;
    private javax.swing.JPanel jP_administrador;
    private javax.swing.JPanel jP_cadastrarAdmin;
    private javax.swing.JPanel jP_cadastrarCliente;
    private javax.swing.JPanel jP_cadastrarCliente1;
    private javax.swing.JPanel jP_cadastrarFuncionario1;
    private javax.swing.JPanel jP_cliente;
    private javax.swing.JPanel jP_cliente1;
    private javax.swing.JPanel jP_container;
    private javax.swing.JPanel jP_funcionario;
    private javax.swing.JPanel jP_listarAdmin;
    private javax.swing.JPanel jP_listarCliente;
    private javax.swing.JPanel jP_listarCliente1;
    private javax.swing.JPanel jP_listarFuncionario;
    private javax.swing.JPanel jP_sair;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
