/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.telas;

import br.edu.util.ControleTelas;
import com.sun.webkit.event.WCKeyEvent;
import java.awt.Color;
import org.jdesktop.swingx.border.DropShadowBorder;


/**
 *
 * @author Lab1
 */


public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeAdmin() {
        initComponents();
        esconderTodosPaineis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jP_listarRecepcionista = new javax.swing.JPanel();
        jL_listarRecepcionista = new javax.swing.JLabel();
        jP_cadastrarAdmin = new javax.swing.JPanel();
        jL_cadastarAdmin = new javax.swing.JLabel();
        jP_cadastrarRecepcionista = new javax.swing.JPanel();
        jL_cadastraRecepcionista = new javax.swing.JLabel();
        jP_recepcionistas = new javax.swing.JPanel();
        jL_recepcionistas = new javax.swing.JLabel();
        jP_clientes = new javax.swing.JPanel();
        jL_clientes = new javax.swing.JLabel();
        jP_medicos = new javax.swing.JPanel();
        jL_medicos = new javax.swing.JLabel();
        jP_listarAdmin = new javax.swing.JPanel();
        jL_listarAdmin = new javax.swing.JLabel();
        jP_listarMedicos = new javax.swing.JPanel();
        jL_listaMedicos = new javax.swing.JLabel();
        jP_cadastrarMedico = new javax.swing.JPanel();
        jL_cadastrarMedicos = new javax.swing.JLabel();
        jP_admin = new javax.swing.JPanel();
        jL_admin = new javax.swing.JLabel();
        jP_cadastrarClientes = new javax.swing.JPanel();
        jL_cadastrarCliente = new javax.swing.JLabel();
        jP_listarClientes = new javax.swing.JPanel();
        jL_listaClientes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 238, 219));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jP_listarRecepcionista.setBackground(new java.awt.Color(92, 179, 184));
        jP_listarRecepcionista.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarRecepcionistaMouseMoved(evt);
            }
        });
        jP_listarRecepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarRecepcionistaMouseExited(evt);
            }
        });

        jL_listarRecepcionista.setBackground(new java.awt.Color(255, 255, 255));
        jL_listarRecepcionista.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_listarRecepcionista.setForeground(new java.awt.Color(255, 255, 255));
        jL_listarRecepcionista.setText("Listra de Recepcionista");

        javax.swing.GroupLayout jP_listarRecepcionistaLayout = new javax.swing.GroupLayout(jP_listarRecepcionista);
        jP_listarRecepcionista.setLayout(jP_listarRecepcionistaLayout);
        jP_listarRecepcionistaLayout.setHorizontalGroup(
            jP_listarRecepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listarRecepcionistaLayout.createSequentialGroup()
                .addComponent(jL_listarRecepcionista)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jP_listarRecepcionistaLayout.setVerticalGroup(
            jP_listarRecepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_listarRecepcionistaLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jL_listarRecepcionista)
                .addContainerGap())
        );

        jPanel1.add(jP_listarRecepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 110, 110));

        jP_cadastrarAdmin.setBackground(new java.awt.Color(92, 152, 185));
        jP_cadastrarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jP_cadastrarAdminMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarAdminMouseMoved(evt);
            }
        });
        jP_cadastrarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_cadastrarAdminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarAdminMouseExited(evt);
            }
        });

        jL_cadastarAdmin.setBackground(new java.awt.Color(241, 238, 219));
        jL_cadastarAdmin.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_cadastarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastarAdmin.setText("Cadastrar Admin");

        javax.swing.GroupLayout jP_cadastrarAdminLayout = new javax.swing.GroupLayout(jP_cadastrarAdmin);
        jP_cadastrarAdmin.setLayout(jP_cadastrarAdminLayout);
        jP_cadastrarAdminLayout.setHorizontalGroup(
            jP_cadastrarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cadastrarAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_cadastarAdmin)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jP_cadastrarAdminLayout.setVerticalGroup(
            jP_cadastrarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_cadastrarAdminLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jL_cadastarAdmin)
                .addContainerGap())
        );

        jPanel1.add(jP_cadastrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 110, 110));

        jP_cadastrarRecepcionista.setBackground(new java.awt.Color(51, 160, 166));
        jP_cadastrarRecepcionista.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarRecepcionistaMouseMoved(evt);
            }
        });
        jP_cadastrarRecepcionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarRecepcionistaMouseExited(evt);
            }
        });

        jL_cadastraRecepcionista.setBackground(new java.awt.Color(241, 238, 219));
        jL_cadastraRecepcionista.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_cadastraRecepcionista.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastraRecepcionista.setText("Cadastrar Recepcionista");

        javax.swing.GroupLayout jP_cadastrarRecepcionistaLayout = new javax.swing.GroupLayout(jP_cadastrarRecepcionista);
        jP_cadastrarRecepcionista.setLayout(jP_cadastrarRecepcionistaLayout);
        jP_cadastrarRecepcionistaLayout.setHorizontalGroup(
            jP_cadastrarRecepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cadastrarRecepcionistaLayout.createSequentialGroup()
                .addComponent(jL_cadastraRecepcionista)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jP_cadastrarRecepcionistaLayout.setVerticalGroup(
            jP_cadastrarRecepcionistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_cadastrarRecepcionistaLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jL_cadastraRecepcionista)
                .addContainerGap())
        );

        jPanel1.add(jP_cadastrarRecepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 110, 110));

        jP_recepcionistas.setBackground(new java.awt.Color(0, 136, 144));
        jP_recepcionistas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_recepcionistasMouseMoved(evt);
            }
        });
        jP_recepcionistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_recepcionistasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_recepcionistasMouseExited(evt);
            }
        });

        jL_recepcionistas.setBackground(new java.awt.Color(241, 238, 219));
        jL_recepcionistas.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_recepcionistas.setForeground(new java.awt.Color(255, 255, 255));
        jL_recepcionistas.setText("Recepcionistas");

        javax.swing.GroupLayout jP_recepcionistasLayout = new javax.swing.GroupLayout(jP_recepcionistas);
        jP_recepcionistas.setLayout(jP_recepcionistasLayout);
        jP_recepcionistasLayout.setHorizontalGroup(
            jP_recepcionistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_recepcionistasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_recepcionistas)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jP_recepcionistasLayout.setVerticalGroup(
            jP_recepcionistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_recepcionistasLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jL_recepcionistas)
                .addContainerGap())
        );

        jPanel1.add(jP_recepcionistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 110, 110));

        jP_clientes.setBackground(new java.awt.Color(0, 94, 145));
        jP_clientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_clientesMouseMoved(evt);
            }
        });
        jP_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_clientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_clientesMouseExited(evt);
            }
        });

        jL_clientes.setBackground(new java.awt.Color(241, 238, 219));
        jL_clientes.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_clientes.setForeground(new java.awt.Color(255, 255, 255));
        jL_clientes.setText("Clientes");

        javax.swing.GroupLayout jP_clientesLayout = new javax.swing.GroupLayout(jP_clientes);
        jP_clientes.setLayout(jP_clientesLayout);
        jP_clientesLayout.setHorizontalGroup(
            jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_clientesLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jL_clientes)
                .addGap(33, 33, 33))
        );
        jP_clientesLayout.setVerticalGroup(
            jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_clientesLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jL_clientes)
                .addContainerGap())
        );

        jPanel1.add(jP_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 110, 110));

        jP_medicos.setBackground(new java.awt.Color(0, 136, 144));
        jP_medicos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_medicosMouseMoved(evt);
            }
        });
        jP_medicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_medicosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_medicosMouseExited(evt);
            }
        });

        jL_medicos.setBackground(new java.awt.Color(241, 238, 219));
        jL_medicos.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_medicos.setForeground(new java.awt.Color(255, 255, 255));
        jL_medicos.setText("Medicos");

        javax.swing.GroupLayout jP_medicosLayout = new javax.swing.GroupLayout(jP_medicos);
        jP_medicos.setLayout(jP_medicosLayout);
        jP_medicosLayout.setHorizontalGroup(
            jP_medicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_medicosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jL_medicos)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jP_medicosLayout.setVerticalGroup(
            jP_medicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_medicosLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jL_medicos)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jP_medicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 110, 110));

        jP_listarAdmin.setBackground(new java.awt.Color(125, 173, 199));
        jP_listarAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarAdminMouseMoved(evt);
            }
        });
        jP_listarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_listarAdminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarAdminMouseExited(evt);
            }
        });

        jL_listarAdmin.setBackground(new java.awt.Color(241, 238, 219));
        jL_listarAdmin.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_listarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jL_listarAdmin.setText("Listar Admin");

        javax.swing.GroupLayout jP_listarAdminLayout = new javax.swing.GroupLayout(jP_listarAdmin);
        jP_listarAdmin.setLayout(jP_listarAdminLayout);
        jP_listarAdminLayout.setHorizontalGroup(
            jP_listarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listarAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_listarAdmin)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jP_listarAdminLayout.setVerticalGroup(
            jP_listarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_listarAdminLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jL_listarAdmin)
                .addContainerGap())
        );

        jPanel1.add(jP_listarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 110, 110));

        jP_listarMedicos.setBackground(new java.awt.Color(92, 179, 184));
        jP_listarMedicos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarMedicosMouseMoved(evt);
            }
        });
        jP_listarMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarMedicosMouseExited(evt);
            }
        });

        jL_listaMedicos.setBackground(new java.awt.Color(241, 238, 219));
        jL_listaMedicos.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_listaMedicos.setForeground(new java.awt.Color(255, 255, 255));
        jL_listaMedicos.setText("Listar Medicos");

        javax.swing.GroupLayout jP_listarMedicosLayout = new javax.swing.GroupLayout(jP_listarMedicos);
        jP_listarMedicos.setLayout(jP_listarMedicosLayout);
        jP_listarMedicosLayout.setHorizontalGroup(
            jP_listarMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listarMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_listaMedicos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_listarMedicosLayout.setVerticalGroup(
            jP_listarMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_listarMedicosLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jL_listaMedicos)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jP_listarMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 110, 110));

        jP_cadastrarMedico.setBackground(new java.awt.Color(51, 160, 166));
        jP_cadastrarMedico.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarMedicoMouseMoved(evt);
            }
        });
        jP_cadastrarMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarMedicoMouseExited(evt);
            }
        });

        jL_cadastrarMedicos.setBackground(new java.awt.Color(241, 238, 219));
        jL_cadastrarMedicos.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_cadastrarMedicos.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastrarMedicos.setText("Cadastrar Medico");

        javax.swing.GroupLayout jP_cadastrarMedicoLayout = new javax.swing.GroupLayout(jP_cadastrarMedico);
        jP_cadastrarMedico.setLayout(jP_cadastrarMedicoLayout);
        jP_cadastrarMedicoLayout.setHorizontalGroup(
            jP_cadastrarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cadastrarMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_cadastrarMedicos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_cadastrarMedicoLayout.setVerticalGroup(
            jP_cadastrarMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_cadastrarMedicoLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jL_cadastrarMedicos)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jP_cadastrarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 110, 110));

        jP_admin.setBackground(new java.awt.Color(0, 94, 145));
        jP_admin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_adminMouseMoved(evt);
            }
        });
        jP_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_adminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_adminMouseExited(evt);
            }
        });

        jL_admin.setBackground(new java.awt.Color(241, 238, 219));
        jL_admin.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_admin.setForeground(new java.awt.Color(255, 255, 255));
        jL_admin.setText("Admin");

        javax.swing.GroupLayout jP_adminLayout = new javax.swing.GroupLayout(jP_admin);
        jP_admin.setLayout(jP_adminLayout);
        jP_adminLayout.setHorizontalGroup(
            jP_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_adminLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jL_admin)
                .addGap(33, 33, 33))
        );
        jP_adminLayout.setVerticalGroup(
            jP_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_adminLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jL_admin)
                .addContainerGap())
        );

        jPanel1.add(jP_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 110, 110));

        jP_cadastrarClientes.setBackground(new java.awt.Color(92, 152, 185));
        jP_cadastrarClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_cadastrarClientesMouseMoved(evt);
            }
        });
        jP_cadastrarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_cadastrarClientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_cadastrarClientesMouseExited(evt);
            }
        });

        jL_cadastrarCliente.setBackground(new java.awt.Color(241, 238, 219));
        jL_cadastrarCliente.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_cadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jL_cadastrarCliente.setText("Cadastrar Cliente");

        javax.swing.GroupLayout jP_cadastrarClientesLayout = new javax.swing.GroupLayout(jP_cadastrarClientes);
        jP_cadastrarClientes.setLayout(jP_cadastrarClientesLayout);
        jP_cadastrarClientesLayout.setHorizontalGroup(
            jP_cadastrarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cadastrarClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_cadastrarCliente)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jP_cadastrarClientesLayout.setVerticalGroup(
            jP_cadastrarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_cadastrarClientesLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jL_cadastrarCliente)
                .addContainerGap())
        );

        jPanel1.add(jP_cadastrarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 110, 110));

        jP_listarClientes.setBackground(new java.awt.Color(125, 173, 199));
        jP_listarClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_listarClientesMouseMoved(evt);
            }
        });
        jP_listarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_listarClientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_listarClientesMouseExited(evt);
            }
        });

        jL_listaClientes.setBackground(new java.awt.Color(241, 238, 219));
        jL_listaClientes.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jL_listaClientes.setForeground(new java.awt.Color(255, 255, 255));
        jL_listaClientes.setText("Lista de Clientes");

        javax.swing.GroupLayout jP_listarClientesLayout = new javax.swing.GroupLayout(jP_listarClientes);
        jP_listarClientes.setLayout(jP_listarClientesLayout);
        jP_listarClientesLayout.setHorizontalGroup(
            jP_listarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_listarClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_listaClientes)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jP_listarClientesLayout.setVerticalGroup(
            jP_listarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_listarClientesLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jL_listaClientes)
                .addContainerGap())
        );

        jPanel1.add(jP_listarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 110, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(909, 764));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //codigo para colocar as sombras nos paineis
    private DropShadowBorder efeitoBorda(){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.black);
        shadow.setShadowSize(10);
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowBottomShadow(true);
        shadow.setShowTopShadow(true);
        return shadow;
    }
    //codigo para cancelar a borda em todas os paineis
    private void efeitoBordaCancelar(){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShowLeftShadow(false);
        shadow.setShowRightShadow(false);
        shadow.setShowBottomShadow(false);
        shadow.setShowTopShadow(false);
        
        jP_admin.setBorder(shadow);
        jP_cadastrarAdmin.setBorder(shadow);
        jP_listarAdmin.setBorder(shadow);
        jP_clientes.setBorder(shadow);
        jP_cadastrarClientes.setBorder(shadow);
        jP_listarClientes.setBorder(shadow);
        jP_medicos.setBorder(shadow);
        jP_cadastrarMedico.setBorder(shadow);
        jP_listarMedicos.setBorder(shadow);
        jP_recepcionistas.setBorder(shadow);
        jP_cadastrarRecepcionista.setBorder(shadow);
        jP_listarRecepcionista.setBorder(shadow);
    }
    private void esconderTodosPaineis(){
        jP_listarRecepcionista.setVisible(false);
        jP_cadastrarAdmin.setVisible(false);
        jP_cadastrarRecepcionista.setVisible(false);
        jP_cadastrarMedico.setVisible(false);
        jP_cadastrarClientes.setVisible(false);
        jP_listarClientes.setVisible(false);
        jP_listarAdmin.setVisible(false);
        jP_listarMedicos.setVisible(false);
    }
    private void principaisPaineis(boolean controle){
        jP_medicos.setVisible(controle);
        jP_clientes.setVisible(controle);
        jP_admin.setVisible(controle);
        jP_recepcionistas.setVisible(controle);
    }
    
 
    private void jP_cadastrarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarAdminMouseMoved
         jP_cadastrarAdmin.setBorder((efeitoBorda()));
    }//GEN-LAST:event_jP_cadastrarAdminMouseMoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
       
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jP_listarRecepcionistaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarRecepcionistaMouseMoved
        jP_listarRecepcionista.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_listarRecepcionistaMouseMoved

    private void jP_listarRecepcionistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarRecepcionistaMouseExited
       efeitoBordaCancelar();
    }//GEN-LAST:event_jP_listarRecepcionistaMouseExited

    private void jP_cadastrarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarAdminMouseExited
        efeitoBordaCancelar();
    }//GEN-LAST:event_jP_cadastrarAdminMouseExited

    private void jP_recepcionistasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_recepcionistasMouseMoved
       jP_recepcionistas.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_recepcionistasMouseMoved

    private void jP_clientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_clientesMouseMoved
        jP_clientes.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_clientesMouseMoved

    private void jP_medicosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_medicosMouseMoved
        jP_medicos.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_medicosMouseMoved

    private void jP_recepcionistasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_recepcionistasMouseExited
        efeitoBordaCancelar();
    }//GEN-LAST:event_jP_recepcionistasMouseExited

    private void jP_clientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_clientesMouseExited
        efeitoBordaCancelar();
    }//GEN-LAST:event_jP_clientesMouseExited

    private void jP_medicosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_medicosMouseExited
        efeitoBordaCancelar();
    }//GEN-LAST:event_jP_medicosMouseExited

    private void jP_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_clientesMouseClicked
        principaisPaineis(false);
        jP_cadastrarClientes.setVisible(true);
        jP_listarClientes.setVisible(true);        
    }//GEN-LAST:event_jP_clientesMouseClicked

    private void jP_cadastrarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarAdminMouseClicked
        if(ControleTelas.telaCadastroClientes == false){
            CadastroCliente cadastroCliente = new CadastroCliente();
            cadastroCliente.setVisible(true);
            ControleTelas.telaCadastroClientes = true;
        }
    }//GEN-LAST:event_jP_cadastrarAdminMouseClicked

    private void jP_listarAdminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarAdminMouseMoved
        jP_listarAdmin.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_listarAdminMouseMoved

    private void jP_listarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarAdminMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarAdminMouseClicked

    private void jP_listarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarAdminMouseExited
        efeitoBordaCancelar();
    }//GEN-LAST:event_jP_listarAdminMouseExited

    private void jP_cadastrarRecepcionistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarRecepcionistaMouseExited
        efeitoBordaCancelar();
    }//GEN-LAST:event_jP_cadastrarRecepcionistaMouseExited

    private void jP_cadastrarRecepcionistaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarRecepcionistaMouseMoved
        jP_cadastrarRecepcionista.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_cadastrarRecepcionistaMouseMoved

    private void jP_listarMedicosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarMedicosMouseMoved
        jP_listarMedicos.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_listarMedicosMouseMoved

    private void jP_listarMedicosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarMedicosMouseExited
        efeitoBordaCancelar();
    }//GEN-LAST:event_jP_listarMedicosMouseExited

    private void jP_cadastrarMedicoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarMedicoMouseMoved
        jP_cadastrarMedico.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_cadastrarMedicoMouseMoved

    private void jP_cadastrarMedicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarMedicoMouseExited
        efeitoBordaCancelar();
    }//GEN-LAST:event_jP_cadastrarMedicoMouseExited

    private void jP_adminMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_adminMouseMoved
        jP_admin.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_adminMouseMoved

    private void jP_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_adminMouseClicked
        principaisPaineis(false);
        jP_cadastrarAdmin.setVisible(true);
        jP_listarAdmin.setVisible(true);   
    }//GEN-LAST:event_jP_adminMouseClicked

    private void jP_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_adminMouseExited
        efeitoBordaCancelar();
    }//GEN-LAST:event_jP_adminMouseExited

    private void jP_cadastrarClientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarClientesMouseMoved
        jP_cadastrarClientes.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_cadastrarClientesMouseMoved

    private void jP_cadastrarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarClientesMouseClicked
        if(ControleTelas.telaListarClientes == false){
            ClientesListar clientesListar = new ClientesListar();
            clientesListar.setVisible(true);
            ControleTelas.telaListarClientes = true;
        }
    }//GEN-LAST:event_jP_cadastrarClientesMouseClicked

    private void jP_cadastrarClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarClientesMouseExited
        efeitoBordaCancelar();
    }//GEN-LAST:event_jP_cadastrarClientesMouseExited

    private void jP_listarClientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarClientesMouseMoved
        jP_listarClientes.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_listarClientesMouseMoved

    private void jP_listarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_listarClientesMouseClicked

    private void jP_listarClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_listarClientesMouseExited
        efeitoBordaCancelar();
    }//GEN-LAST:event_jP_listarClientesMouseExited

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // Duplo clique
        if (evt.getClickCount() == 2 ) {
            principaisPaineis(true);
            esconderTodosPaineis();
        }
    
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jP_cadastrarAdminMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_cadastrarAdminMouseDragged
       jP_cadastrarAdmin.setBorder(efeitoBorda());
    }//GEN-LAST:event_jP_cadastrarAdminMouseDragged

    private void jP_recepcionistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_recepcionistasMouseClicked
        principaisPaineis(false);
        jP_cadastrarRecepcionista.setVisible(true);
        jP_listarRecepcionista.setVisible(true);   
    }//GEN-LAST:event_jP_recepcionistasMouseClicked

    private void jP_medicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_medicosMouseClicked
        principaisPaineis(false);
        jP_cadastrarMedico.setVisible(true);
        jP_listarMedicos.setVisible(true);   
    }//GEN-LAST:event_jP_medicosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_admin;
    private javax.swing.JLabel jL_cadastarAdmin;
    private javax.swing.JLabel jL_cadastraRecepcionista;
    private javax.swing.JLabel jL_cadastrarCliente;
    private javax.swing.JLabel jL_cadastrarMedicos;
    private javax.swing.JLabel jL_clientes;
    private javax.swing.JLabel jL_listaClientes;
    private javax.swing.JLabel jL_listaMedicos;
    private javax.swing.JLabel jL_listarAdmin;
    private javax.swing.JLabel jL_listarRecepcionista;
    private javax.swing.JLabel jL_medicos;
    private javax.swing.JLabel jL_recepcionistas;
    private javax.swing.JPanel jP_admin;
    private javax.swing.JPanel jP_cadastrarAdmin;
    private javax.swing.JPanel jP_cadastrarClientes;
    private javax.swing.JPanel jP_cadastrarMedico;
    private javax.swing.JPanel jP_cadastrarRecepcionista;
    private javax.swing.JPanel jP_clientes;
    private javax.swing.JPanel jP_listarAdmin;
    private javax.swing.JPanel jP_listarClientes;
    private javax.swing.JPanel jP_listarMedicos;
    private javax.swing.JPanel jP_listarRecepcionista;
    private javax.swing.JPanel jP_medicos;
    private javax.swing.JPanel jP_recepcionistas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
