/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.telas;

import br.edu.DAO.AtendimentoDAO;
import br.edu.anotacoes.Atendimento;
import br.edu.anotacoes.Cliente;
import br.edu.tableModel.AtendimentoTableModel;
import br.edu.tableModel.ClienteTableModel;
import br.edu.util.ControleTelas;
import java.awt.Color;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.border.DropShadowBorder;

/**
 *
 * @author cra-dti-04
 */
public class ListarAtendimento extends javax.swing.JFrame {

    /**
     * Creates new form ListarAtendimento
     */
    public ListarAtendimento() {
        initComponents();
        ControleTelas.telaListarAtendimento = true;
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jP_Excluir1 = new javax.swing.JPanel();
        jL_editar = new javax.swing.JLabel();
        jP_Excluir = new javax.swing.JPanel();
        jL_excluir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 375, 275));

        jP_Excluir1.setBackground(new java.awt.Color(0, 102, 102));
        jP_Excluir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_Excluir1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_editar.setBackground(new java.awt.Color(0, 102, 102));
        jL_editar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_editar.setText("Editar");
        jL_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jL_editar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_editarMouseMoved(evt);
            }
        });
        jL_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_editarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_editarMouseExited(evt);
            }
        });
        jP_Excluir1.add(jL_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        getContentPane().add(jP_Excluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 100, 40));

        jP_Excluir.setBackground(new java.awt.Color(0, 102, 102));
        jP_Excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jP_Excluir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_excluir.setBackground(new java.awt.Color(0, 102, 102));
        jL_excluir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jL_excluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_excluir.setText("Excluir");
        jL_excluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jL_excluir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_excluirMouseMoved(evt);
            }
        });
        jL_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_excluirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_excluirMouseExited(evt);
            }
        });
        jP_Excluir.add(jL_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        getContentPane().add(jP_Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private DropShadowBorder efeitoBorda(){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLACK);
        shadow.setShadowSize(5);
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowBottomShadow(true);
        shadow.setShowTopShadow(true);
        return shadow;
    }
    //codigo para cancelar a borda em todas os paineis
    private void efeitoBordaCancelar(javax.swing.JPanel painel){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShowLeftShadow(false);
        shadow.setShowRightShadow(false);
        shadow.setShowBottomShadow(false);
        shadow.setShowTopShadow(false);
        
        painel.setBorder(shadow);
    }
    
    private void jL_excluirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_excluirMouseMoved
        jP_Excluir.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_excluirMouseMoved

    private void jL_excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_excluirMouseClicked
        if(getAtendimento() !=  null){
            if(JOptionPane.showConfirmDialog(null, "Certeza que deseja deletar") == 0){
                try {
                    AtendimentoDAO atendimentoDAO = new AtendimentoDAO();
                    atendimentoDAO.deletar(getAtendimento());
                } catch (Exception e) {
                    System.out.println("Erro no delete do atendimento " +e);
                }
                JOptionPane.showMessageDialog(null, "Atendimento deletado com sucesso");
            }
        }
        atualizarTabela();
    }//GEN-LAST:event_jL_excluirMouseClicked

    private void jL_excluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_excluirMouseExited
        efeitoBordaCancelar(jP_Excluir);
    }//GEN-LAST:event_jL_excluirMouseExited

    private void jL_editarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_editarMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_editarMouseMoved

    private void jL_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_editarMouseClicked
       System.out.println(ControleTelas.telaCadastroAtendimento);
        System.out.println(ControleTelas.telaCadastroAtendimento);
        System.out.println(ControleTelas.telaCadastroAtendimento);
        if(ControleTelas.telaCadastroAtendimento == false){
            CadastrarAtendimento cadastrarAtendimento = new CadastrarAtendimento(getAtendimento());
            cadastrarAtendimento.setVisible(true);
        }
    }//GEN-LAST:event_jL_editarMouseClicked

    private void jL_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_editarMouseExited
        
    }//GEN-LAST:event_jL_editarMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       ControleTelas.telaListarAtendimento = true;
    }//GEN-LAST:event_formWindowClosing

    public void atualizarTabela(){
        AtendimentoDAO atendimentoDAO = new AtendimentoDAO();
        List<Atendimento> lista = atendimentoDAO.listar();
        AtendimentoTableModel atendimentoTableModel = new AtendimentoTableModel(lista);
        jTable1.setModel(atendimentoTableModel);
    }
    
    private Atendimento getAtendimento(){
        int linha = jTable1.getSelectedRow();
        if (linha >= 0) {
            AtendimentoTableModel atm = (AtendimentoTableModel) jTable1.getModel();
            Atendimento atendimento = atm.getValueAt(linha);
            return atendimento;
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarAtendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_editar;
    private javax.swing.JLabel jL_excluir;
    private javax.swing.JPanel jP_Excluir;
    private javax.swing.JPanel jP_Excluir1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
