/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.telas;

import br.edu.DAO.ClienteDAO2;
import br.edu.anotacoes.Cliente;
import br.edu.tableModel.ClienteTableModel;
import br.edu.util.ControleTelas;
import br.edu.util.Util;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.border.DropShadowBorder;

/**
 *
 * @author Lab1
 */
public class ListarClientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public ListarClientes() {
        initComponents();
        ControleTelas.telaListarClientes = true;
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JP_conteudo = new javax.swing.JPanel();
        jP_voltar = new javax.swing.JPanel();
        jL_voltar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jP_excluir = new javax.swing.JPanel();
        jL_excluir = new javax.swing.JLabel();
        jP_editar = new javax.swing.JPanel();
        jL_editar = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        JP_conteudo.setBackground(new java.awt.Color(36, 47, 65));
        JP_conteudo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jP_voltar.setBackground(new java.awt.Color(0, 102, 102));
        jP_voltar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_voltarMouseMoved(evt);
            }
        });
        jP_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_voltarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_voltarMouseExited(evt);
            }
        });

        jL_voltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL_voltar.setForeground(new java.awt.Color(255, 255, 255));
        jL_voltar.setText("          Voltar");
        jL_voltar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_voltarMouseMoved(evt);
            }
        });
        jL_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_voltarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_voltarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jP_voltarLayout = new javax.swing.GroupLayout(jP_voltar);
        jP_voltar.setLayout(jP_voltarLayout);
        jP_voltarLayout.setHorizontalGroup(
            jP_voltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_voltar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jP_voltarLayout.setVerticalGroup(
            jP_voltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_voltarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jL_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JP_conteudo.add(jP_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 120, 40));

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JP_conteudo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        JP_conteudo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        jP_excluir.setBackground(new java.awt.Color(0, 102, 102));
        jP_excluir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_excluirMouseMoved(evt);
            }
        });
        jP_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_excluirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_excluirMouseExited(evt);
            }
        });

        jL_excluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL_excluir.setForeground(new java.awt.Color(255, 255, 255));
        jL_excluir.setText("          Excluir");
        jL_excluir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_excluirMouseMoved(evt);
            }
        });
        jL_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_excluirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_excluirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jP_excluirLayout = new javax.swing.GroupLayout(jP_excluir);
        jP_excluir.setLayout(jP_excluirLayout);
        jP_excluirLayout.setHorizontalGroup(
            jP_excluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jP_excluirLayout.setVerticalGroup(
            jP_excluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_excluirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jL_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JP_conteudo.add(jP_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 120, 40));

        jP_editar.setBackground(new java.awt.Color(0, 102, 102));
        jP_editar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_editarMouseMoved(evt);
            }
        });
        jP_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_editarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_editarMouseExited(evt);
            }
        });

        jL_editar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL_editar.setForeground(new java.awt.Color(255, 255, 255));
        jL_editar.setText("          Editar");
        jL_editar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_editarMouseMoved(evt);
            }
        });
        jL_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_editarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_editarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jP_editarLayout = new javax.swing.GroupLayout(jP_editar);
        jP_editar.setLayout(jP_editarLayout);
        jP_editarLayout.setHorizontalGroup(
            jP_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_editar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jP_editarLayout.setVerticalGroup(
            jP_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_editarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jL_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JP_conteudo.add(jP_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 120, 40));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        JP_conteudo.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JP_conteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    protected static void atualizarTabela(){
        ClienteDAO2 clienteDAO = new ClienteDAO2();
        ClienteTableModel clienteTableModel = new ClienteTableModel(clienteDAO.listar());
        jTable1.setModel(clienteTableModel);
    }
    private Cliente getCliente(){
        int linha = jTable1.getSelectedRow();
        if (linha >= 0) {
            ClienteTableModel tbm = (ClienteTableModel) jTable1.getModel();
            Cliente cliente = tbm.getValueAt(linha);
            return cliente;
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum cliente selecionado");
            return null;
        }
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ControleTelas.telaListarClientes = false;
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cliente cliente = getCliente();
        if(cliente !=  null){
            if(JOptionPane.showConfirmDialog(null, "Certeza que deseja deletar o cliente " + cliente.getNome()) == 0){
                try {
                    ClienteDAO2 clienteDAO2 = new ClienteDAO2();
                    clienteDAO2.deletar(cliente);
                    atualizarTabela();
                } catch (Exception e) {
                    System.out.println("Erro no delete do cliente " +e);
                }
                JOptionPane.showMessageDialog(null, "Cliente deletado com sucesso");
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(ControleTelas.telaCadastroClientes == false && getCliente() != null){
            CadastroCliente cac = new CadastroCliente(getCliente());
            cac.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() > 1) {  
            if(ControleTelas.telaAtendimentoGenerico == false){
                ControleTelas.telaAtendimentoGenerico = true;
                ListarAtendimentoMedico listarAtendimentoGenerico = new ListarAtendimentoMedico("cliente", getCliente());
                listarAtendimentoGenerico.setVisible(true);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    }//GEN-LAST:event_formMouseClicked

    private void jL_voltarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_voltarMouseMoved
        jP_voltar.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_voltarMouseMoved

    private void jL_voltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_voltarMouseExited
        efeitoBordaCancelar(jP_voltar);
    }//GEN-LAST:event_jL_voltarMouseExited

    private void jP_voltarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_voltarMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_voltarMouseMoved

    private void jP_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_voltarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_voltarMouseClicked

    private void jP_voltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_voltarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_voltarMouseExited

    private void jL_excluirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_excluirMouseMoved
        jP_excluir.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_excluirMouseMoved

    private void jL_excluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_excluirMouseExited
        efeitoBordaCancelar(jP_excluir);
    }//GEN-LAST:event_jL_excluirMouseExited

    private void jP_excluirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_excluirMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_excluirMouseMoved

    private void jP_excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_excluirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_excluirMouseClicked

    private void jP_excluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_excluirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_excluirMouseExited

    private void jL_editarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_editarMouseMoved
        jP_editar.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_editarMouseMoved

    private void jL_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_editarMouseExited
        efeitoBordaCancelar(jP_editar);
    }//GEN-LAST:event_jL_editarMouseExited

    private void jP_editarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_editarMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_editarMouseMoved

    private void jP_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_editarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_editarMouseClicked

    private void jP_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_editarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_editarMouseExited

    private void jL_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_editarMouseClicked
       {                                         
        if(ControleTelas.telaCadastroClientes == false && getCliente() != null){
            CadastroCliente cac = new CadastroCliente(getCliente());
            cac.setVisible(true);
        }
    }
    }//GEN-LAST:event_jL_editarMouseClicked

    private void jL_excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_excluirMouseClicked
       {                                         
        Cliente cliente = getCliente();
        if(cliente !=  null){
            if(JOptionPane.showConfirmDialog(null, "Certeza que deseja deletar o cliente " + cliente.getNome()) == 0){
                try {
                    ClienteDAO2 clienteDAO2 = new ClienteDAO2();
                    clienteDAO2.deletar(cliente);
                    atualizarTabela();
                } catch (Exception e) {
                    System.out.println("Erro no delete do cliente " +e);
                }
                JOptionPane.showMessageDialog(null, "Cliente deletado com sucesso");
            }
        }
        
    } 
    }//GEN-LAST:event_jL_excluirMouseClicked

    private void jL_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_voltarMouseClicked
        // TODO add your handling code here:
                    this.dispose();

    }//GEN-LAST:event_jL_voltarMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            HashMap parametros = new HashMap();
            Util.imprimir("Relatorios\\ListaClientes.jrxml", parametros);
        } catch (Exception e) {
            System.out.println("Erro na geração do prontuario " + e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarClientes().setVisible(true);
            }
        });
    }
    //codigo para colocar as sombras nos paineis
    private DropShadowBorder efeitoBorda(){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.black);
        shadow.setShadowSize(5);
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowBottomShadow(true);
        shadow.setShowTopShadow(true);
        return shadow;
    }
    //codigo para cancelar a borda em todas os paineis
    private void efeitoBordaCancelar(javax.swing.JPanel painel){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShowLeftShadow(false);
        shadow.setShowRightShadow(false);
        shadow.setShowBottomShadow(false);
        shadow.setShowTopShadow(false);
        
        painel.setBorder(shadow);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_conteudo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jL_editar;
    private javax.swing.JLabel jL_excluir;
    private javax.swing.JLabel jL_voltar;
    private javax.swing.JPanel jP_editar;
    private javax.swing.JPanel jP_excluir;
    private javax.swing.JPanel jP_voltar;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
