/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.telas;

import br.edu.DAO.RecepcionistaDAO;
import br.edu.anotacoes.Recepcionista;
import br.edu.tableModel.RecepcionistaTableModel;
import br.edu.util.ControleTelas;
import br.edu.util.Util;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.border.DropShadowBorder;

/**
 *
 * @author Usuario
 */
public class ListarRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form ListarRecepcionista
     */
    public ListarRecepcionista() {
        initComponents();
        atualizarTabela();
        ControleTelas.telaListarRecepcionista = true;
    }
    protected static void atualizarTabela(){
        RecepcionistaDAO recepcionistaDAO = new RecepcionistaDAO();
        RecepcionistaTableModel recepcionistaTableModel = new RecepcionistaTableModel(recepcionistaDAO.listar());
        jTable1.setModel(recepcionistaTableModel);
    }
    private Recepcionista getRecepcionista(){
        int linha = jTable1.getSelectedRow();
        if (linha >= 0) {
            RecepcionistaTableModel tbm = (RecepcionistaTableModel) jTable1.getModel();
            Recepcionista recepcionista = tbm.getValueAt(linha);
            return recepcionista;
        }
        return null;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JP_conteudo = new javax.swing.JPanel();
        jP_excluir = new javax.swing.JPanel();
        jL_excluir1 = new javax.swing.JLabel();
        jP_editar = new javax.swing.JPanel();
        jL_editar1 = new javax.swing.JLabel();
        jP_Relatorio = new javax.swing.JPanel();
        jL_Relatorio = new javax.swing.JLabel();
        jP_voltar = new javax.swing.JPanel();
        jL_voltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTable1);

        JP_conteudo.setBackground(new java.awt.Color(36, 47, 65));
        JP_conteudo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jP_excluir.setBackground(new java.awt.Color(0, 102, 102));
        jP_excluir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_excluirMouseMoved(evt);
            }
        });
        jP_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_excluirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_excluirMouseExited(evt);
            }
        });
        jP_excluir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_excluir1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL_excluir1.setForeground(new java.awt.Color(255, 255, 255));
        jL_excluir1.setText("        Excluir");
        jL_excluir1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_excluir1MouseMoved(evt);
            }
        });
        jL_excluir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_excluir1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_excluir1MouseExited(evt);
            }
        });
        jP_excluir.add(jL_excluir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        JP_conteudo.add(jP_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 110, 40));

        jP_editar.setBackground(new java.awt.Color(0, 102, 102));
        jP_editar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_editarMouseMoved(evt);
            }
        });
        jP_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_editarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_editarMouseExited(evt);
            }
        });
        jP_editar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_editar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL_editar1.setForeground(new java.awt.Color(255, 255, 255));
        jL_editar1.setText("       Editar");
        jL_editar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_editar1MouseMoved(evt);
            }
        });
        jL_editar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_editar1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_editar1MouseExited(evt);
            }
        });
        jP_editar.add(jL_editar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 105, 40));

        JP_conteudo.add(jP_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, 40));

        jP_Relatorio.setBackground(new java.awt.Color(0, 102, 102));
        jP_Relatorio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_RelatorioMouseMoved(evt);
            }
        });
        jP_Relatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_RelatorioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_RelatorioMouseExited(evt);
            }
        });
        jP_Relatorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_Relatorio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL_Relatorio.setForeground(new java.awt.Color(255, 255, 255));
        jL_Relatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Relatorio.setText("Gerar Relatorio");
        jL_Relatorio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_RelatorioMouseMoved(evt);
            }
        });
        jL_Relatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_RelatorioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_RelatorioMouseExited(evt);
            }
        });
        jP_Relatorio.add(jL_Relatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        JP_conteudo.add(jP_Relatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 40));

        jP_voltar.setBackground(new java.awt.Color(0, 102, 102));
        jP_voltar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jP_voltarMouseMoved(evt);
            }
        });
        jP_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_voltarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jP_voltarMouseExited(evt);
            }
        });
        jP_voltar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_voltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jL_voltar.setForeground(new java.awt.Color(255, 255, 255));
        jL_voltar.setText("          Voltar");
        jL_voltar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jL_voltarMouseMoved(evt);
            }
        });
        jL_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_voltarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_voltarMouseExited(evt);
            }
        });
        jP_voltar.add(jL_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        JP_conteudo.add(jP_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JP_conteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ControleTelas.telaListarRecepcionista = false;
    }//GEN-LAST:event_formWindowClosing

    private void jL_voltarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_voltarMouseMoved
        jP_voltar.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_voltarMouseMoved

    private void jL_voltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_voltarMouseExited
        efeitoBordaCancelar(jP_voltar);
    }//GEN-LAST:event_jL_voltarMouseExited

    private void jP_voltarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_voltarMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_voltarMouseMoved

    private void jP_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_voltarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_voltarMouseClicked

    private void jP_voltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_voltarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_voltarMouseExited

    private void jL_excluir1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_excluir1MouseMoved
        jP_excluir.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_excluir1MouseMoved

    private void jL_excluir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_excluir1MouseClicked
        {                                        
        // TODO add your handling code here:
        Recepcionista recepcionista = getRecepcionista();
        if(recepcionista !=  null){
            if(JOptionPane.showConfirmDialog(null, "Certeza que deseja deletar a recepcionista " + recepcionista.getNome()) == 0){
                try {
                    RecepcionistaDAO recepcionistaDAO = new RecepcionistaDAO();
                    recepcionistaDAO.deletar(recepcionista);
                } catch (Exception e) {
                    System.out.println("Erro no delete do recepcionista " +e);
                }
                JOptionPane.showMessageDialog(null, "Recepcionista deletado com sucesso");
            }
        }
        atualizarTabela();
    } 
    }//GEN-LAST:event_jL_excluir1MouseClicked

    private void jL_excluir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_excluir1MouseExited
        efeitoBordaCancelar(jP_excluir);
    }//GEN-LAST:event_jL_excluir1MouseExited

    private void jP_excluirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_excluirMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_excluirMouseMoved

    private void jP_excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_excluirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_excluirMouseClicked

    private void jP_excluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_excluirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_excluirMouseExited

    private void jL_editar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_editar1MouseMoved
        jP_editar.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_editar1MouseMoved

    private void jL_editar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_editar1MouseClicked
        {                                         
        if(getRecepcionista() != null){
            CadastroRecepcionista cadastroRecepcionista = new CadastroRecepcionista(getRecepcionista());
            cadastroRecepcionista.setVisible(true);
        }
    }
    }//GEN-LAST:event_jL_editar1MouseClicked

    private void jL_editar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_editar1MouseExited
        efeitoBordaCancelar(jP_editar);
    }//GEN-LAST:event_jL_editar1MouseExited

    private void jP_editarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_editarMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_editarMouseMoved

    private void jP_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_editarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_editarMouseClicked

    private void jP_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_editarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_editarMouseExited

    private void jL_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_voltarMouseClicked
        // TODO add your handling code here:
                    this.dispose();

    }//GEN-LAST:event_jL_voltarMouseClicked

    private void jL_RelatorioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_RelatorioMouseMoved
        jP_Relatorio.setBorder(efeitoBorda());
    }//GEN-LAST:event_jL_RelatorioMouseMoved

    private void jL_RelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_RelatorioMouseClicked
        try {
            HashMap parametros = new HashMap();
            Util.imprimir("Relatorios\\ListarRecepcionista.jrxml", parametros);
        } catch (Exception e) {
            System.out.println("Erro na geração do prontuario " + e);
        }
    }//GEN-LAST:event_jL_RelatorioMouseClicked

    private void jL_RelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_RelatorioMouseExited
        efeitoBordaCancelar(jP_Relatorio);
    }//GEN-LAST:event_jL_RelatorioMouseExited

    private void jP_RelatorioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_RelatorioMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_RelatorioMouseMoved

    private void jP_RelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_RelatorioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_RelatorioMouseClicked

    private void jP_RelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_RelatorioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jP_RelatorioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarRecepcionista().setVisible(true);
            }
        });
    }
    //codigo para colocar as sombras nos paineis
    private DropShadowBorder efeitoBorda(){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.black);
        shadow.setShadowSize(5);
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowBottomShadow(true);
        shadow.setShowTopShadow(true);
        return shadow;
    }
    //codigo para cancelar a borda em todas os paineis
    private void efeitoBordaCancelar(javax.swing.JPanel painel){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShowLeftShadow(false);
        shadow.setShowRightShadow(false);
        shadow.setShowBottomShadow(false);
        shadow.setShowTopShadow(false);
        
        painel.setBorder(shadow);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_conteudo;
    private javax.swing.JLabel jL_Relatorio;
    private javax.swing.JLabel jL_editar1;
    private javax.swing.JLabel jL_excluir1;
    private javax.swing.JLabel jL_voltar;
    private javax.swing.JPanel jP_Relatorio;
    private javax.swing.JPanel jP_editar;
    private javax.swing.JPanel jP_excluir;
    private javax.swing.JPanel jP_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
